sonar.projectKey=youssefahmedmoh_sonarqube-quality-gate-demo_07eff891-56bf-42ad-b477-76f1d1faeca6

sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
